const testData =
    '[{"name":"Algeria","topLevelDomain":[".dz"],"alpha2Code":"DZ",'
    '"alpha3Code":"DZA","callingCodes":["213"],"capital":"Algiers","altSpellings":'
    '["DZ","Dzayer","Algérie"],"region":"Africa","subregion":"Northern Africa",'
    '"population":40400000,"latlng":[28.0,3.0],"demonym":"Algerian","area":'
    '2381741.0,"gini":35.3,"timezones":["UTC+01:00"],"borders":["AO","BJ","ZA",'
    '"ESH","MRT","MLI","MAR"],"nativeName":"الجزائر","numericCode":"012",'
    '"currencies":[{"code":"DZD","name":"Algerian dinar","symbol":"د.ج"}],'
    '"languages":[{"iso639_1":"ar","iso639_2":"ara","name":"Arabic","nativeName":'
    '"العربية"}],"translations":{"de":"Algerien","es":"Argelia","fr":"Algérie",'
    '"ja":"アルジェリア","it":"Algeria","br":"Argélia","pt":"Argélia","nl":'
    '"Algerije","hr":"Alžir","fa":"الجزایر"},'
    '"flag":"https://restcountries.eu/data/dza.svg","regionalBlocs":'
    '[{"acronym":"AU","name":"African Union","otherAcronyms":[],"otherNames":'
    '["الاتحاد الأفريقي","Union africaine","União Africana","Unión Africana",'
    '"Umoja wa Afrika"]},{"acronym":"AL","name":"Arab League","otherAcronyms":[],'
    '"otherNames":["جامعة الدول العربية","Jāmiʻat ad-Duwal al-ʻArabīyah",'
    '"League of Arab States"]}],"cioc":"ALG"},{"name":"Angola","topLevelDomain":'
    '[".ao"],"alpha2Code":"AO","alpha3Code":"AGO","callingCodes":["244"],"capital":'
    '"Luanda","altSpellings":["AO","República de Angola","ʁɛpublika de an'
    'ɡɔla"],"region":"Africa","subregion":"Middle Africa","population":25868000,'
    '"latlng":[-12.5,18.5],"demonym":"Angolan","area":1246700.0,"gini":58.6,'
    '"timezones":["UTC+01:00"],"borders":["DZ","BJ","ZA","NAM"],"nativeName":'
    '"Angola","numericCode":"024","currencies":[{"code":"AOA","name":"Angolan '
    'kwanza","symbol":"Kz"}],"languages":[{"iso639_1":"pt","iso639_2":"por",'
    '"name":"Portuguese","nativeName":"Português"}],"translations":{"de":"Angola",'
    '"es":"Angola","fr":"Angola","ja":"アンゴラ","it":"Angola","br":"Angola","pt":'
    '"Angola","nl":"Angola","hr":"Angola","fa":"آنگولا"},"flag":'
    '"https://restcountries.eu/data/ago.svg","regionalBlocs":[{"acronym":"AU",'
    '"name":"African Union","otherAcronyms":[],"otherNames":["الاتحاد الأفريقي",'
    '"Union africaine","União Africana","Unión Africana","Umoja wa Afrika"]}],'
    '"cioc":"ANG"},{"name":"Benin","topLevelDomain":[".bj"],"alpha2Code":"BJ",'
    '"alpha3Code":"BEN","callingCodes":["229"],"capital":"Porto-Novo",'
    '"altSpellings":["BJ","Republic of Benin","République du Bénin"],"region":'
    '"Africa","subregion":"Western Africa","population":10653654,"latlng":'
    '[9.5,2.25],"demonym":"Beninese","area":112622.0,"gini":38.6,"timezones":'
    '["UTC+01:00"],"borders":["DZ","AO","ZA","TGO"],"nativeName":"Bénin",'
    '"numericCode":"204","currencies":[{"code":"XOF","name":"West African CFA '
    'franc","symbol":"Fr"}],"languages":[{"iso639_1":"fr","iso639_2":"fra",'
    '"name":"French","nativeName":"français"}],"translations":{"de":"Benin",'
    '"es":"Benín","fr":"Bénin","ja":"ベナン","it":"Benin","br":"Benin","pt":'
    '"Benim","nl":"Benin","hr":"Benin","fa":"بنین"},"flag":'
    '"https://restcountries.eu/data/ben.svg","regionalBlocs":[{"acronym":"AU",'
    '"name":"African Union","otherAcronyms":[],"otherNames":["الاتحاد الأفريقي",'
    '"Union africaine","União Africana","Unión Africana","Umoja wa '
    'Afrika"]}],"cioc":"BEN"},{"name":"South Africa","topLevelDomain":[".za"],'
    '"alpha2Code":"ZA","alpha3Code":"ZAF","callingCodes":["27"],"capital":'
    '"Pretoria","altSpellings":["ZA","RSA","Suid-Afrika","Republic of South '
    'Africa"],"region":"Africa","subregion":"Southern Africa","population":'
    '55653654,"latlng":[-29.0,24.0],"demonym":"South African","area":1221037.0,'
    '"gini":63.1,"timezones":["UTC+02:00"],"borders":["DZ","AO","BJ","NAM",'
    '"SWZ","ZWE"],"nativeName":"South Africa","numericCode":"710","currencies":'
    '[{"code":"ZAR","name":"South African rand","symbol":"R"}],"languages":'
    '[{"iso639_1":"af","iso639_2":"afr","name":"Afrikaans","nativeName":'
    '"Afrikaans"},{"iso639_1":"en","iso639_2":"eng","name":"English",'
    '"nativeName":"English"},{"iso639_1":"nr","iso639_2":"nbl","name":'
    '"Southern Ndebele","nativeName":"isiNdebele"},{"iso639_1":"st","iso639_2"'
    ':"sot","name":"Southern Sotho","nativeName":"Sesotho"},{"iso639_1":"ss",'
    '"iso639_2":"ssw","name":"Swati","nativeName":"SiSwati"},{"iso639_1":"tn",'
    '"iso639_2":"tsn","name":"Tswana","nativeName":"Setswana"},{"iso639_1":"ts",'
    '"iso639_2":"tso","name":"Tsonga","nativeName":"Xitsonga"},{"iso639_1":"ve",'
    '"iso639_2":"ven","name":"Venda","nativeName":"Tshivenḓa"},{"iso639_1":"xh",'
    '"iso639_2":"xho","name":"Xhosa","nativeName":"isiXhosa"},{"iso639_1":"zu",'
    '"iso639_2":"zul","name":"Zulu","nativeName":"isiZulu"}],"translations":'
    '{"de":"Republik Südafrika","es":"República de Sudáfrica","fr":"Afrique du '
    'Sud","ja":"南アフリカ","it":"Sud Africa","br":"República Sul-Africana",'
    '"pt":"República Sul-Africana","nl":"Zuid-Afrika","hr":"Južnoafrička '
    'Republika","fa":"آفریقای جنوبی"},"flag":'
    '"https://restcountries.eu/data/zaf.svg","regionalBlocs":[{"acronym":"AU",'
    '"name":"African Union","otherAcronyms":[],"otherNames":["الاتحاد الأفريقي",'
    '"Union africaine","União Africana","Unión Africana",'
    '"Umoja wa Afrika"]}],"cioc":"RSA"}]';
